# File: Makefile
#
# Summary:
# This file contains the build script for modules and their configuration.
#
# Copyright (C) 2017 - Shukant Pal

KModule_Make:
	make -C ./ObjectManager ObMake
	make -C ./ModuleFramework MfMake
	make -C ./ResourceManager RsMake
